api:
  port: 8082
  host:
  advertiseHost: rating
serviceDiscovery:
  consul:
    address: http://consul-server.consul.svc.cluster.local:8500
ingester:
  kafka:
    address: localhost:9092
database:
  dsn: root:password@/movieexample
