apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rating
  template:
    metadata:
      labels:
        app: rating
    spec:
      containers:
        - name: rating
          image: movie/rating:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: DB_DSN
              value: "root:password@tcp(mysql.mysql.svc.cluster.local:3306)/movieexample"
            - name: KAFKA_ADDRESS
              value: "kafka.kafka.svc.cluster.local:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: rating
spec:
  selector:
    app: rating
  ports:
    - name: grpc
      port: 8082
      targetPort: 8082
